<?php 
	echo $this->tag->linkTo(array(
		'permissions',
		'<i class="icon-lock"></i> Gestion Permissions',
		'class' => 'btn btn-primary'
	));
?>
&nbsp;
<?php 
	echo $this->tag->linkTo(array(
		'seo',
		'<i class="icon-group"></i> Gestion Profiles',
		'class' => 'btn btn-primary'
	));
?>
&nbsp;
<?php 
	echo $this->tag->linkTo(array(
		'users/manage',
		'<i class="icon-user"></i> Gestion Users',
		'class' => 'btn btn-primary'
	));
?>