<div class="page-header">
    <h1>
        Mot de passe
        <small>
            <i class="icon-double-angle-right"></i>
            Modifier mon mot de passe
        </small>
    </h1>
</div><!-- /.page-header -->

<div class="row">
    <div class="col-xs-12">
        <div class="center">
            <form method="post" class="form-inline" autocomplete="off" action="<?php echo $this->url->get('users/changePassword'); ?>">
                <div class="form-group">
                    <label class="sr-only" for="password">Votre nouveau mot de passe</label>
                    <?php echo $form->render('password'); ?>
                </div>
                <div class="form-group">
                    <label class="sr-only" for="confirmPassword">Confirmez le nouveau mot de passe</label>
                    <?php echo $form->render('confirmPassword'); ?>
                </div>
                <?php echo $this->tag->submitButton(array('Changer mon mot de passe', 'class' => 'btn btn-primary btn-xs')); ?>
            </form>
        </div>
    </div>
</div>
