<div class="page-header">
	<h1>
		Mes compétences
		<small>
			<i class="icon-double-angle-right"></i>
			Naviguez et trouvez vos compétences!!!
		</small>
	</h1>
</div><!-- /.page-header -->

<div class="row">
	<div class="col-xs-12">
		<!-- PAGE CONTENT BEGINS -->

		<div class="row">
			<div class="col-sm-9 col-xs-12">
				<div class="widget-box">
					<div class="widget-header header-color-blue2">
						<h4 class="lighter smaller">Choisissez vos compétences</h4>
					</div>

					<div class="widget-body">
						<div class="widget-main padding-8">
							<div id="tree1" class="tree"></div>
						</div>
					</div>
				</div>
			</div>

			<div class="col-sm-3 col-xs-12">
				<div class="widget-box">
					<div class="widget-header header-color-green2">
						<h4 class="lighter smaller">Votre choix de compétences</h4>
					</div>

					<div class="widget-body">
						<div class="widget-main padding-8">
							<form action="" method="post">
								<div class="tags" id="skills-tags">
									<span id="no-skills">Aucune compétence renseignée</span>
								</div>
								<button id="submit-skills" type="submit" class="btn btn-sm btn-danger hidden">Mettre mes compétences a jour</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>

		<script type="text/javascript">
			var $assets = "assets";//this will be used in fuelux.tree-sampledata.js
		</script>

		<!-- PAGE CONTENT ENDS -->
	</div><!-- /.col -->
</div><!-- /.row -->