<div class="page-header">
    <h1>
        Ajouter un nouveau projet
        <small>
            <i class="icon-double-angle-right"></i>

        </small>
    </h1>
</div><!-- /.page-header -->

<div class="row">
    <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->
            
        <!-- PAGE CONTENT ENDS -->
    </div><!-- /.col -->
</div><!-- /.row -->
<script type="text/javascript">
var pkey = '<?php echo $user->_id; ?>';
</script>