
<div class="page-header">
    <h1>
        Ajouter un nouveau projet
        <small>
            <i class="icon-double-angle-right"></i>

        </small>
    </h1>
</div><!-- /.page-header -->

<div class="row">
    <div class="col-md-6 col-xs-12">
        <!-- PAGE CONTENT BEGINS -->
            <?php echo Phalcon\Tag::form(array("projects/create", "method" => "post")); ?>
                                            <fieldset>
                                                <label class="block clearfix">
                                                    <span class="block input-icon input-icon-right">
                                                        <?php echo $formCreate->render('name') ?>
                                                        <i class="icon-keyboard"></i>
                                                    </span>
                                                </label>

                                                <div class="ace-spinner touch-spinner" style="width: 140px;">
                                                    <div class="input-group">
                                                        <?php echo $formCreate->render('nb_users_max') ?>
                                                    <div class="spinner-buttons input-group-btn">  
                                                        <button type="button" class="btn spinner-up btn-xs ">
                                                            <i class="icon-caret-up"></i>
                                                                </button>
                                                        <button type="button" class="btn spinner-down btn-xs ">
                                                            <i class="icon-caret-down"></i>
                                                                </button> 
                                                                 </div>
                                                             </div>
                                                         </div>
                                                     
                                                <label class="block clearfix">
                                                    <span class="block input-icon input-icon-right">
                                                        <?php echo $formCreate->render('start_date') ?>
                                                        <i class="icon-calendar"></i>
                                                    </span>
                                                </label>

                                                <label class="block clearfix">
                                                    <span class="block input-icon input-icon-right">
                                                        <?php echo $formCreate->render('end_date') ?>
                                                        <i class="icon-calendar"></i>
                                                    </span>
                                                </label>

                                                <label class="block clearfix">
                                                    <span class="block input-icon input-icon-right">
                                                        <?php echo $formCreate->render('description') ?>
                                                        <i class="icon-file-text-alt"></i>
                                                    </span>
                                                </label>
                                                
                                                    <button type="submit" class="width-35 pull-right btn btn-sm btn-primary">
                                                        <i class="icon-ok"></i>
                                                        valider
                                                    </button>
                                                </div>

                                                <div class="space-4"></div>
                                            </fieldset>
                                        <?php echo Phalcon\Tag::endForm(); ?>
       
        <!-- PAGE CONTENT ENDS -->
    </div><!-- /.col -->
</div><!-- /.row -->
<script type="text/javascript">
var pkey = '<?php echo $user->_id; ?>';
</script>