<div class="page-header">
	<h1>
		Projets
		<small>
			<i class="icon-double-angle-right"></i>
			<?php
										echo $this->tag->linkTo(array(
								          'projects/create',
								          '<i class="icon-plus"></i>Ajouter un projet',
								          'class' => 'btn btn-sm btn-danger pull-right'
								          ));
									?>
					</small>
	</h1>
</div><!-- /.page-header -->

<div class="row">
	<div class="col-xs-12">
		<!-- PAGE CONTENT BEGINS -->
		<!--Liste des projets -->
		<div class="row">
			<div class="col-xs-12">
				<div class="table-responsive">
					<table id="user-table" class="table table-striped table-bordered table-hover">
						<thead>
							<tr>
								<th>Nom du projet</th>
								<th>Chef de projet</th>
								<th>Avancement</th>
								<th>Date de fin</th>
								<th>Nbr Pers.</th>
								<th>Statut</th>
							</tr>
						</thead>

						<tbody>
							<?php foreach($projects as $project): ?>
							<tr>
								
								<!-- /.col Nom du projet -->
								<td>
									<?php
										echo $this->tag->linkTo(array(
								          'projects/view/'.$project->_id,
									      ucwords($project->name),
									      'target' => '_blank'
								          ));
									?>
								</td>

								<!-- /.col Chef de projet -->
								<td><?php
										echo $this->tag->linkTo(array(
								        'projects/view/'.$project->_id,
									    ucwords($project->project_master),
									    'target' => '_blank'
								        ));
									?>

								 </td>

								<!-- /.col Avancement -->
								<td>
									<div class="progress progress-striped" data-percent="<?php echo $project->progress.'%'?>">
										<div class="progress-bar progress-bar-success" style="width: <?php echo $project->progress.'%'?>;"></div>
									</div>
								</td>
								
								<!-- /.col Date de Fin -->
								<td><?php
									echo $this->tag->linkTo(array(
								    'projects/view/'.$project->_id,
									ucwords($project->end_date),
									'target' => '_blank'
								      ));
								 ?>
								</td>
								
								<!-- /.col Nbr. Personne dans le projet -->
								<td><?php
									
								?></td>
								
								<!-- /.col Statut -->
								<td><?php
									echo $this->tag->linkTo(array(
								    'projects/view/'.$project->_id,
									ucwords($project->status_name),
									'target' => '_blank'
								    ));
									?>
								</td>

							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div><!-- /.col -->
</div><!-- /.row -->