<div class="page-header">
	<h1>
		Projets
		<small>
			<i class="icon-double-angle-right"></i>
			<?php
										echo $this->tag->linkTo(array(
								          'projects/create',
								          '<i class="icon-plus"></i>Ajouter un projet',
								          'class' => 'btn btn-sm btn-danger pull-right'
								          ));
									?>
					</small>
	</h1>

</div><!-- /.page-header -->

<div class="row">
	<div class="col-xs-12">
		<!-- PAGE CONTENT BEGINS -->
		<!--Liste des projets -->
		<div class="row">
			<div class="col-xs-12">
				<div class="table-responsive">
					<table id="user-table" class="table table-striped table-bordered table-hover">
						<thead>
							<tr>
								<th class="center">
									<label>
										<input type="checkbox" class="ace" />
										<span class="lbl"></span>
									</label>
								</th>
								<th>Nom du projet</th>
								<th>Chef de projet</th>
								<th>Avancement</th>
								<th>Date de fin</th>
								<th>Nbr Pers.</th>
								<th>Etat</th>
							</tr>
						</thead>

						<tbody>
							<?php foreach($users as $user): ?>
							<tr>
								<td class="center">
									<label>
										<input type="checkbox" class="ace" />
										<span class="lbl"></span>
									</label>
								</td>

								<td>
									<?php
										echo $this->tag->linkTo(array(
								          'users/view/'.$user->_id,
									      ucwords($user->name).' '.strtoupper($user->surname),
									      'target' => '_blank'
								          ));
									?>
								</td>
								<td><?php
									foreach ($profiles as $profile) {
										if($user->profile_id == $profile->_id){
											echo '<span class="label label-sm label-'.$profile->style.'">'.$profile->name.'</span>';
											break;
										}
									}
								 ?></td>
								<td><?php
									foreach ($promotions as $promotion) {
										if($user->promotion_id == $promotion->_id){
											echo $promotion->name;
											break;
										}
									}
								 ?></td>

								<td>
									<div class="visible-md visible-lg hidden-sm hidden-xs action-buttons">
										<?php
											echo $this->tag->linkTo(array(
									          	'users/edit/'.$user->_id,
										      	'<i class="icon-pencil bigger-130"></i>',
										      	'class' => 'green',
										      	'data-rel' => 'tooltip',
										      	'title' => 'Editer'
									          ));
										?>

										<?php
											echo $this->tag->linkTo(array(
									          	'users/delete/'.$user->_id,
										      	'<i class="icon-trash bigger-130"></i>',
										      	'class' => 'red',
										      	'id' => 'delete',
										      	'data-rel' => 'tooltip',
										      	'title' => 'Supprimer'
									          ));
										?>
									</div>

									<div class="visible-xs visible-sm hidden-md hidden-lg">
										<div class="inline position-relative">
											<button class="btn btn-minier btn-yellow dropdown-toggle" data-toggle="dropdown">
												<i class="icon-caret-down icon-only bigger-120"></i>
											</button>

											<ul class="dropdown-menu dropdown-only-icon dropdown-yellow pull-right dropdown-caret dropdown-close">
												<li>
													<?php
														echo $this->tag->linkTo(array(
												          	'users/edit/'.$user->_id,
													      	'<span class="green"><i class="icon-pencil bigger-120"></i></span>',
													      	'class' => 'green',
													      	'data-rel' => 'tooltip',
													      	'title' => 'Editer'
												          ));
													?>
												</li>

												<li>
													<?php
														echo $this->tag->linkTo(array(
												          	'users/delete/'.$user->_id,
													      	'<span class="red"><i class="icon-trash bigger-120"></i></span>',
													      	'class' => 'red',
													      	'id' => 'delete',
													      	'data-rel' => 'tooltip',
													      	'title' => 'Supprimer'
												          ));
													?>
												</li>
												<li>
													<?php 
							                            echo $this->tag->linkTo(array(
							                                'quick-mail/'.$user->_id.'/'.ucwords($user->firstname).'-'.(($user->wedding_surname != null) ? strtoupper($user->wedding_surname) : strtoupper($user->surname)).'/'.$this->security->hash($user->_id.'-'.ucwords($user->firstname).'-'.(($user->wedding_surname != null) ? strtoupper($user->wedding_surname) : strtoupper($user->surname))),
							                                '<i class="icon-envelope-alt bigger-130"></i>',
							                                'class' => 'orange',
													      	'data-rel' => 'tooltip',
													      	'title' => 'Mail'
												      	));
							                        ?>
												</li>
											</ul>
										</div>
									</div>
								</td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div><!-- /.col -->
</div><!-- /.row -->