 <div class="page-header">
    <?php if($updateAllowed): ?>
    <h1>
        Mon Projet
        <small>
            <i class="icon-double-angle-right"></i>
            Voir et modifier les informations de mon projet
        </small>
    </h1>
<?php else: ?>
	<h1>
        <?php echo ucwords($projects->name)?>
        <small>
            <i class="icon-double-angle-right"></i>
            <?php echo $projects->status_name ?>
        </small>
    </h1>
<?php endif; ?>
</div><!-- /.page-header -->
<div class="widget-body">
    <div class="itemdiv dialogdiv">
        <div class="user">
            <img alt="John's Avatar" src="assets/avatars/avatar.png">
        </div>

        <div class="body">
            <?php foreach ($userProject as $usersProject){ 
                    if($usersProject->user_id == $users->_id){
                     echo '<div class="name">'.$users->name.'</div>';
                     break;
                    }
                 }   
                ?>
        </div>
    </div>
</div>