<div class="page-header">
    <h1>
        La Dream Team
        <small>
            <i class="icon-double-angle-right"></i>
            où presque
        </small>
    </h1>
</div><!-- /.page-header -->

<div class="row">
	<div class="col-md-4">
		<figure>
			<span class="profile-picture">           
				<?php 
					echo $this->tag->image(array(
						'img/kevin.jpg',
						'alt' => 'Kevin BALINI',
	                    'class' => 'img-responsive'
					)); 
				?>
			</span>
			<figcaption class="team-fig">
				Kevin BALINI (Baloche)
			</figcaption>
		</figure>
	</div>
	<div class="col-md-4">
		<figure>
			<span class="profile-picture">           
				<?php 
					echo $this->tag->image(array(
						'img/sabri.jpg',
						'alt' => 'Sabri DALI',
	                    'class' => 'img-responsive'
					)); 
				?>
			</span>
			<figcaption class="team-fig">
				Sabri DALI (Baalgrid)
			</figcaption>
		</figure>
	</div>
	<div class="col-md-4">
		<figure>
			<span class="profile-picture">           
				<?php 
					echo $this->tag->image(array(
						'img/romain.jpg',
						'alt' => 'Romain BONGIBAULT',
	                    'class' => 'img-responsive'
					)); 
				?>
			</span>
			<figcaption class="team-fig">
				Romain BONGIBAULT (Rbt)
			</figcaption>
		</figure>
	</div>
</div>