
	<div class="main-container">
		<div class="main-content">
			<div class="row">
				<div class="col-sm-10 col-sm-offset-1">
				<?php echo $this->flash->output(); ?>
				<?php echo $this->flashSession->output(); ?>
					<div class="login-container">
						<div class="center">
							<h1>
								<i class="icon-leaf green"></i>
								<span class="red">SPASM</span>
								<span class="white">Application</span>
							</h1>
							<h4 class="blue">&copy; DreamTeam ou presque...</h4>
						</div>

						<div class="space-6"></div>

						<div class="position-relative">
							<div id="login-box" class="login-box visible widget-box no-border">
								<div class="widget-body">
									<div class="widget-main">
										<h4 class="header blue lighter bigger">
											<i class="icon-coffee green"></i>
											Entrer vos informations
										</h4>

										<div class="space-6"></div>

										<?php echo Phalcon\Tag::form(array("session/login", "method" => "post")); ?>
											<fieldset>
												<label class="block clearfix">
													<span class="block input-icon input-icon-right">
														<?php echo $formLogin->render('login') ?>
														<i class="icon-user"></i>
													</span>
												</label>

												<label class="block clearfix">
													<span class="block input-icon input-icon-right">
														<?php echo $formLogin->render('password') ?>
														<i class="icon-lock"></i>
													</span>
												</label>

												<div class="space"></div>

												<div class="clearfix">
													<label class="inline">
														<?php echo $formLogin->render('remember') ?>
														<span class="lbl">  <?php echo $formLogin->getLabel('remember'); ?></span>
													</label>

													<button type="submit" class="width-35 pull-right btn btn-sm btn-primary">
														<i class="icon-key"></i>
														Connexion
													</button>
												</div>

												<div class="space-4"></div>
											</fieldset>
										<?php echo Phalcon\Tag::endForm(); ?>

									</div><!-- /widget-main -->

								</div><!-- /widget-body -->
							</div><!-- /login-box -->

							
						</div><!-- /position-relative -->
					</div>
				</div><!-- /.col -->
			</div><!-- /.row -->
		</div>
	</div><!-- /.main-container -->
	<script>
	$('body').addClass('login-layout');
	</script>